[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "nevobo_api"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
requests = ">=2.32.3,<3"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
feedparser = "*"
pytest = ">=8.3.4,<9"
